# src/constants.py

kategori_mapping = {
    'Pusat Kesenian': 'Budaya',
    'Pusat kebudayaan': 'Budaya',
    'Museum': 'Museum',
    'Museum Seni': 'Museum',
    'Museum Sejarah Lokal': 'Museum',
    'Museum Interaktif': 'Museum',
    'Monumen': 'Monumen',
    'Patung': 'Monumen',
    'Pura': 'Religi',
    'Pantai': 'Alam',
    'Gunung': 'Alam',
    'Taman Kota': 'Tempat Bermain',
    'Taman': 'Tempat Bermain',
    'Taman Hiburan': 'Tempat Bermain',
    'Taman Rekreasi Air': 'Tempat Bermain',
    'Taman bermain': 'Tempat Bermain',
    'Taman Ekologi': 'Alam',
    'Pasar': 'Pasar',
    'Pasar tradisional': 'Pasar',
    'Toko Pakaian': 'Pasar',
    'Tujuan Wisata': 'Tempat Bermain',
    'Kota Hantu': 'Budaya',
}